@startuml

package view {
    class UserInterface {
        - scanner: Scanner
        - teacherService: TeacherService
        - teachingRequirementService: TeachingRequirementService
        - trainingSessionService: TrainingSessionService
        + getInstance(): UserInterface
        + setTeacherService(TeacherService): void
        + setTeachingRequirementService(TeachingRequirementService): void
        + setTrainingSessionService(TrainingSessionService): void
        + displayMainMenu(): void
    }
}

package model {
    class TeachingRequirement {
        - id: int
        - subject: String
        - qualificationsRequired: List<String>
        - experienceRequired: String
        - startTime: Time
        - daysOfWeek: List<String>
        - teacher: Teacher
    }

    class Teacher {
        - id: int
        - name: String
        - twoHourSlotAvailabilities: List<Time>
        - daysOfWeekAvailable: List<String>
        - qualifications: List<String>
        - experience: String
        - canTeach: List<String>
        - trainingSessions: List<TrainingSession>
        - teachingRequirements: List<TeachingRequirement>
    }

    class TrainingSession {
        - id: int
        - day: String
        - twoHourSlotStartTime: Time
        - teacher: Teacher
        - subject: String
    }
}

package service {
    interface GenericDAO {
        + addEntity(T): void
        + getEntity(int): Optional<T>
        + updateEntity(T): void
        + removeEntity(T): void
        + getAllEntities(): List<T>
    }

    class FileGenericDAO {
        - entities: Map<Integer, T>
        - filePath: String
        - entityType: Class<T>
    }

    class TeacherService {
        - teacherDAO: GenericDAO<Teacher>
    }

    class TeachingRequirementService {
        - teachingRequirementDAO: GenericDAO<TeachingRequirement>
    }

    class TrainingSessionService {
        - trainingSessionDAO: GenericDAO<TrainingSession>
    }
}

interface Identifiable {
    + getId(): int
}

UserInterface ..> TeacherService : uses >
UserInterface ..> TeachingRequirementService : uses >
UserInterface ..> TrainingSessionService : uses >

Teacher ..|> Identifiable : implements
TeachingRequirement ..|> Identifiable : implements
TrainingSession ..|> Identifiable : implements

Teacher "1" -- "M" TeachingRequirement : fulfils >
Teacher "J" -- "N" TrainingSession : attends >

TeacherService ..> Teacher : uses
TeachingRequirementService ..> TeachingRequirement : uses
TrainingSessionService ..> TrainingSession : uses

FileGenericDAO ..> GenericDAO : implements
TeacherService -- FileGenericDAO : uses
TeachingRequirementService -- FileGenericDAO : uses
TrainingSessionService -- FileGenericDAO : uses

@enduml
